server:
  port: 8082

spring:
  application:
    name: USER-SERVICE
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://psqldb-do-user-16227599-0.c.db.ondigitalocean.com:25060/digitaldata
    username: doadmin
    password: AVNS_qkA4cCdf8CkRSO3BBv7
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 600000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL92Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: jahonovjavohir0@gmail.com
    password: xohjjhlanadjlhjp
    properties:
      mjaail:
        smtp:
          auth: true
      mail:
        smtp:
          starttls:
            enable: true
jwt:
  secret:
    key: 753778214125442A472D4B6150645367566B59703373367639792F423F452848567890iuyiu67567886578uyutuio7865467897654678965467uior678545
  access:
    expiry: 86400000
  refresh:
    expiry: 604800000
